artifact_uri: file:///c:/Users/ADMIN/Desktop/Project_ANPR/runs/mlflow/227072752260318798/e5a9418f9fea4c5fbecf4e35850a6720/artifacts
end_time: null
entry_point_name: ''
experiment_id: '227072752260318798'
lifecycle_stage: active
run_id: e5a9418f9fea4c5fbecf4e35850a6720
run_name: train5
run_uuid: e5a9418f9fea4c5fbecf4e35850a6720
source_name: ''
source_type: 4
source_version: ''
start_time: 1745042518892
status: 1
tags: []
user_id: ADMIN
